Universal link support
satispay/magento2-plugin pull request #23
Opened 2022-04-07 11:07 UTC by MichaelBattistonBitbull

add payment id from satispay api to magento payment transaction id in payment controller, refactor api call (for redirect_url)

2022-04-07 12:11 UTC, springerin requested changes

2022-04-07 12:11 UTC, springerin commented on Controller/Payment/Index.php
>              }
loggerei il caso in cui il payment non è settato perché è una situazione di errore che non ci aspettiamo succeda.

2022-04-07 15:33 UTC, springerin approved these changes

2022-04-19 16:21 UTC, stvnmsh approved these changes

2022-04-19 16:21 UTC, merged